apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-1
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
      - name: my-app
        image: darryl443/my-app-1:latest
        ports:
        - containerPort: 3000
---
apiVersion:  v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: my-app-1
